config/routes.rb
Rails.application.routes.draw do

  root 'page#home'

  get 'sign_in', to: 'sessions#new'
  delete 'sign_out', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :projects, only: [:index] do
    resources :reminder_groups do
      collection do
        get 'collection'
      end
    end

    resources :reminder_schedules
  end

  get 'channels', to: 'channels#index'
  get 'projects', to: 'projects#index'
  get 'channels', to: 'callflows#index'

end

app/views/layouts/_config.html.erb
<script>
window.config = {
	host: '<%= root_url %>'
}

</script>

app/views/layouts/_footer.html.erb
<footer class='copyright'>
  <p>&copy; Copyright 
    <a href='http://www.instedd.org' style='text-decoration:none;'>
      <img src='http://www.ilabsoutheastasia.org/wp-content/themes/instedd_v3/images/favicon.ico' />
      InSTEDD
    </a>
  </p>
</footer>

app/views/layouts/_login_bar.html.erb
<% if account_singed_in? %>


<div class="dropdown">

  <a  class="blog-nav-item dropdown-toggle" 
      id="dropdownMenu1"
      data-toggle="dropdown">
    <%= current_account.email %>
    <span class="caret"></span>
  </a>

  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation">
     <%= link_to "Sign out", sign_out_path, tabindex: -1, 
                                            method: :delete,
                                            data: {confirm: 'Are you sure you want to sign out'} %>
     </li>
  </ul>
</div>
<% end %>

app/views/layouts/_nav_bar.html.erb
<div class="blog-masthead">
  <div class='container'>
    <nav class="blog-nav">
      <div class='l-side action-menu'>

        <a class='blog-nav-item' ui-sref= 'projects' > 
          <%= ENV["APP_NAME"] %>
        </a>
      </div>
      <div class='r-side profile-menu'> <%= render 'layouts/login_bar' %> </div>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" ng-app='reminder'>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "VerboiceReminder" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= render 'layouts/config' %>
  </head>
  <body ng-controller="BaseController" ng-init="init()">

    <%= render 'layouts/nav_bar' %>
    <div class="container app-container">

      <div class="main-content">
        <div ui-view></div>
      </div>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/sign_in.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "signin", :media => "all" %>
  </head>
  <body>

    <%= render 'layouts/nav_bar' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div> <!-- /container -->

  </body>
</html>